
create table "MANAGER".USERS
(
	USERID INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1) not null primary key,
	FNAME VARCHAR(50) not null,
	LNAME VARCHAR(50) not null,
        USERNAME VARCHAR(50) not null,
        PASSWORD VARCHAR(50) not null
);

create table "MANAGER".TRANSACTIONS
(
	TRXID INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1) not null,
	USERID integer not null,
	MONTH VARCHAR(10) not null,
	TRXYEAR INTEGER not null,
	DAY INTEGER not null,
	ENVID INTEGER not null,
	TRXTYPE VARCHAR(10),
	TRXAMOUNT DECIMAL(8),
	TRXDESCRIPTION VARCHAR(250),
        CONSTRAINT fk_userid FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

create table "MANAGER".ENVELOPES
(
	ENVID INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1) not null,
	USERID INTEGER not null,
	DATECREATED DATE,
	ENVNAME VARCHAR(50) not null,
	BUDGET DECIMAL(9),
	TRXTOTAL DECIMAL(9),
	primary key (ENVID),
        CONSTRAINT fk_userid_2 FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

create table "MANAGER".HISTORIES
(
	MONTH INTEGER not null,
	TRXYEAR INTEGER not null,
	TOTALBUDGET DECIMAL(9) not null,
	ENVTOTALS DECIMAL(9) not null,
	USERID INTEGER not null,
	primary key (MONTH, TRXYEAR),
        CONSTRAINT fk_userid_3 FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

ALTER TABLE "MANAGER".TRANSACTIONS ADD CONSTRAINT fk_envid FOREIGN KEY (ENVID) REFERENCES ENVELOPES(ENVID)
;
